# -*- coding: utf-8 -*-
"""Clinical RAG FastAPI service.

Thin transport layer around the existing retrieval/generation pipeline.
No core logic lives here — the pipeline is called as-is and its full
GenerationResult is serialised and returned.

Run with:
    uvicorn api.main:app --reload

Endpoints
---------
GET  /health            — API, Qdrant connectivity, and index status.
GET  /v1/meta           — Model/collection metadata.
POST /v1/answer         — Answer a clinical question (calls pipeline.answer_question).
GET  /v1/chunks/{id}    — Retrieve a chunk by its chunk_id.
GET  /v1/corpus         — The guideline documents behind the index.
GET  /v1/evaluation     — The frozen retrieval evaluation, served verbatim from disk.
GET  /docs              — Swagger UI (auto-generated by FastAPI).
GET  /redoc             — ReDoc UI (auto-generated by FastAPI).
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import sys
from contextlib import asynccontextmanager
from functools import lru_cache
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

# Ensure project root is on the path so imports work regardless of cwd
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from generation.config import load_settings as load_generation_settings  # noqa: E402
from generation.parsing import AnswerParseError  # noqa: E402
from generation.pipeline import answer_question  # noqa: E402
from generation.providers import (  # noqa: E402
    SAFE_PROVIDER_MESSAGE,
    MissingAPIKeyError,
    ProviderError,
)
from vectordb.retriever import QdrantRetriever  # noqa: E402
from vectordb.schema import (  # noqa: E402
    COLLECTION_DISTANCE,
    EXPECTED_DIM,
    EXPECTED_MODEL,
    EXPECTED_REVISION,
)

log = logging.getLogger("clinical_rag.api")

# ---------------------------------------------------------------------------
# Application state — one retriever (with one embedded model) for the process
# ---------------------------------------------------------------------------

_retriever: QdrantRetriever | None = None


def _configure_torch_threads() -> None:
    """Pin the encoder's thread count to the container's real CPU allowance.

    PyTorch sizes its intra-op thread pool from the number of cores it can SEE,
    not from the cgroup quota the container is actually allowed. On a hosted
    container that reports many cores while granting a fraction of one, the pool
    is oversubscribed and the threads spend their time contending rather than
    working: encoding one short query took 28 s in production against 90 ms on a
    developer machine, with the vector store ruled out at ~0.5 s.

    Set TORCH_NUM_THREADS to tune it; 1 is the right default for a
    single-request-at-a-time service, where there is no throughput to win from
    intra-op parallelism anyway.

    This runs in the API process only. `ingestion/chunking.py` -- which built the
    frozen index -- is deliberately untouched, so no indexed vector can shift.
    """
    try:
        import torch
    except ImportError:  # pragma: no cover - torch ships with sentence-transformers
        return
    try:
        threads = max(1, int(os.environ.get("TORCH_NUM_THREADS", "1")))
    except ValueError:
        threads = 1
    torch.set_num_threads(threads)
    log.info("Encoder threads pinned to %d (visible cores: %s)", threads, os.cpu_count())


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup: initialise retriever and warm the embedding model.

    We intentionally do NOT crash on failure so that /health can report the
    error gracefully and the service remains queryable for diagnostics.
    """
    global _retriever
    try:
        _configure_torch_threads()
        _retriever = QdrantRetriever()
        # Touch the model property so it is loaded once at startup, not on the
        # first /v1/answer request (which would add latency for that caller).
        _ = _retriever.model
        log.info(
            "Retriever ready — collection=%s  model=%s",
            _retriever.settings.collection,
            _retriever.model_name,
        )
    except Exception as exc:  # noqa: BLE001
        log.error("Failed to initialise retriever: %s", exc)
    yield
    # No explicit teardown required for the in-process Qdrant client.


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Clinical RAG API",
    description=(
        "Thin FastAPI service layer over the AAA clinical guideline RAG pipeline. "
        "Calls the existing retrieval and generation logic without modification."
    ),
    version="1.0.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------

class AnswerRequest(BaseModel):
    """Body for POST /v1/answer."""

    question: str = Field(
        ...,
        description="The clinical guideline question to answer.",
        min_length=1,
        examples=["What diameter threshold triggers elective AAA repair?"],
    )
    top_k: int | None = Field(
        None,
        ge=1,
        description="Number of chunks to retrieve from the vector store. "
                    "Defaults to the value configured in generation settings.",
    )
    threshold: float | None = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Minimum similarity score for a chunk to be used as evidence. "
                    "Defaults to the configured score threshold (0.75).",
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

#: Frozen artifacts served read-only to the UI. Nothing here is recomputed:
#: the files are the ones the published evaluation was written from, and each
#: response carries the SHA-256 of the bytes that were actually read, so a
#: client can prove it is looking at the frozen record and not a live rerun.
_FROZEN_ARTIFACTS: dict[str, Path] = {
    "evaluation_results": ROOT / "eval" / "final_evaluation_results.json",
    "evaluation_summary": ROOT / "eval" / "final_evaluation_summary.json",
    "index_meta": ROOT / "data" / "embeddings" / "index_meta.json",
    "document_metadata": ROOT / "data" / "processed" / "document_metadata.json",
    "integrity_report": ROOT / "eval" / "integrity_report.json",
}


@lru_cache(maxsize=None)
def _read_frozen(name: str) -> tuple[Any, str]:
    """Read one frozen artifact and return `(parsed, sha256_of_bytes)`.

    Cached because these files never change while the service is running --
    they are build-time artifacts, not state. The digest is of the raw bytes,
    so it is comparable with `eval/final_artifact_hashes.json`.
    """
    path = _FROZEN_ARTIFACTS[name]
    raw = path.read_bytes()
    return json.loads(raw.decode("utf-8")), hashlib.sha256(raw).hexdigest()


def _frozen_or_503(name: str) -> tuple[Any, str]:
    try:
        return _read_frozen(name)
    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Frozen artifact '{name}' is not present in this deployment.",
        ) from exc
    except (json.JSONDecodeError, OSError) as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Frozen artifact '{name}' could not be read: {exc}",
        ) from exc


def _require_retriever() -> QdrantRetriever:
    if _retriever is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "Retriever not initialised. Qdrant may be unavailable or the "
                "embedding model failed to load at startup."
            ),
        )
    return _retriever


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get(
    "/health",
    summary="Health check",
    description="Returns API status, Qdrant connectivity, and index readiness.",
    tags=["ops"],
)
def health_check() -> dict[str, Any]:
    qdrant_ok = False
    index_ok = False
    points: int | None = None

    if _retriever is not None:
        try:
            col_info = _retriever.client.get_collection(_retriever.settings.collection)
            qdrant_ok = True
            index_ok = col_info.status.name == "GREEN"
            points = col_info.points_count
        except Exception:  # noqa: BLE001
            pass

    # Whether an LLM key is configured is reported here so a client can say
    # "live generation is unavailable" BEFORE a question is asked, instead of
    # discovering it from a 503 on /v1/answer. Only the boolean is exposed --
    # never the key, and never any part of it.
    try:
        gen = load_generation_settings()
        llm = {
            "configured": bool(gen.api_key),
            "provider": gen.provider,
            "model": gen.model,
        }
    except Exception as exc:  # noqa: BLE001 - a bad provider name must not 500 /health
        llm = {"configured": False, "provider": None, "model": None, "error": str(exc)}

    return {
        "status": "ok" if (qdrant_ok and index_ok) else "degraded",
        "qdrant": qdrant_ok,
        "index": index_ok,
        "points": points,
        "retriever": _retriever is not None,
        "llm": llm,
    }


@app.get(
    "/v1/meta",
    summary="Index and model metadata",
    description="Exposes the pinned model/revision, collection name, dimensions, and chunk count.",
    tags=["meta"],
)
def get_meta() -> dict[str, Any]:
    retriever = _require_retriever()

    try:
        col_info = retriever.client.get_collection(retriever.settings.collection)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Qdrant unavailable: {exc}",
        ) from exc

    # Build-time provenance, read from the index's own manifest. Served so a
    # client can display which chunk set the running collection was built from
    # without trusting anything the UI hardcodes.
    try:
        index_meta, index_meta_sha = _read_frozen("index_meta")
    except Exception:  # noqa: BLE001 - provenance is additive; meta must still answer
        index_meta, index_meta_sha = {}, None

    gen = None
    try:
        settings = load_generation_settings()
        gen = {
            "provider": settings.provider,
            "model": settings.model,
            "api_key_supplied": bool(settings.api_key),
            "top_k": settings.top_k,
            "score_threshold": settings.score_threshold,
            "temperature": settings.temperature,
        }
    except Exception:  # noqa: BLE001
        gen = None

    return {
        "model": EXPECTED_MODEL,
        "revision": EXPECTED_REVISION,
        "dimensions": EXPECTED_DIM,
        "collection": retriever.settings.collection,
        "chunk_count": col_info.points_count,
        "index_status": col_info.status.name,
        "distance": COLLECTION_DISTANCE,
        "vector_store": "Qdrant",
        "connection": retriever.settings.describe(),
        "index_provenance": {
            "source_chunks_file": index_meta.get("source_chunks_file"),
            "source_chunks_sha256": index_meta.get("source_chunks_sha256"),
            "indexed_chunk_ids_sha256": index_meta.get("indexed_chunk_ids_sha256"),
            "n_vectors": index_meta.get("n_vectors"),
            "token_limit": index_meta.get("token_limit"),
            "max_chunk_tokens": index_meta.get("max_chunk_tokens"),
            "built_at_utc": index_meta.get("created_at_utc"),
            "index_meta_sha256": index_meta_sha,
        },
        "generation": gen,
    }


@app.post(
    "/v1/answer",
    summary="Answer a clinical question",
    description=(
        "Calls the existing generation pipeline (retrieve → threshold gate → "
        "safety gate → generate → validate) and returns the full GenerationResult. "
        "No fake or fallback answers are produced — if the pipeline refuses, the "
        "refusal reason is included in the response."
    ),
    tags=["rag"],
)
def answer(req: AnswerRequest) -> dict[str, Any]:
    retriever = _require_retriever()

    try:
        result = answer_question(
            query=req.question,
            retriever=retriever,
            top_k=req.top_k,
            threshold=req.threshold,
        )
    except MissingAPIKeyError as exc:
        # The variable NAME is safe to state and is what an operator needs; the
        # exception text is logged rather than returned, on the same rule as
        # every other upstream failure below.
        log.error("LLM provider API key not configured: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "The language model provider is not configured for this deployment, "
                "so no answer can be generated."
            ),
        ) from exc
    except AnswerParseError as exc:
        # AnswerParseError subclasses ValueError, so it MUST be caught before
        # the ValueError branch below. It means the model returned something
        # that is not a JSON answer object (truncated, or prose) -- an upstream
        # failure, not a bad request. No answer is synthesised: the caller is
        # told generation failed.
        log.error("Model returned an unparseable answer: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "The language model did not return an answer in the required format, "
                "so nothing was produced. No answer was fabricated in its place."
            ),
        ) from exc
    except ProviderError as exc:
        # Rate limit, timeout, refused connection, empty completion. Upstream,
        # so 502 rather than 500 -- and again, never a fabricated answer.
        #
        # The exception text names the vendor, the model, the HTTP status and the
        # upstream body, which for a rate limit carries the account organisation
        # id and billing URLs. That is operator diagnostics, not caller-facing
        # content: it is logged here and replaced with SAFE_PROVIDER_MESSAGE in
        # the response.
        log.error("LLM provider call failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=SAFE_PROVIDER_MESSAGE,
        ) from exc
    except ValueError as exc:
        # pipeline.answer_question raises ValueError for an empty/invalid query,
        # and the retriever for one over the length limit.
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        # Qdrant connection error, network timeout, etc. Same rule: the detail is
        # logged, the caller is told what happened without the internals.
        log.exception("Unhandled error while answering a question")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="The question could not be answered because of an internal error.",
        ) from exc

    payload = result.to_dict()

    # Structured stage timings. Durations, gate name and provider only: no
    # question text, no prompt, no retrieved passage, no credential. This is the
    # observability that was missing when a request could hang for four minutes
    # with nothing to say where the time went.
    timings = payload.get("timings_ms") or {}
    completion = (payload.get("generation") or {}).get("completion") or {}
    log.info(
        "answer stages_ms=%s total_ms=%s provider=%s refused=%s gate=%s citations=%d",
        {k: v for k, v in timings.items() if k != "total"},
        timings.get("total"),
        completion.get("provider"),
        payload.get("refused"),
        (payload.get("refusal") or {}).get("gate"),
        len((payload.get("answer") or {}).get("citations") or []),
    )
    return payload


@app.get(
    "/v1/corpus",
    summary="The guideline corpus behind the index",
    description=(
        "The authoritative documents the index was built from, read from "
        "data/processed/document_metadata.json, plus the number of indexed "
        "chunks each one contributes (counted in Qdrant, not assumed)."
    ),
    tags=["meta"],
)
def get_corpus() -> dict[str, Any]:
    docs, docs_sha = _frozen_or_503("document_metadata")

    # Per-document chunk counts come from the live collection, so the page shows
    # what is actually indexed rather than what a build report once said.
    counts: dict[str, int] = {}
    counts_source = "unavailable"
    if _retriever is not None:
        try:
            offset = None
            while True:
                points, offset = _retriever.client.scroll(
                    collection_name=_retriever.settings.collection,
                    limit=512,
                    with_payload=["document_id"],
                    with_vectors=False,
                    offset=offset,
                )
                for point in points:
                    doc_id = (point.payload or {}).get("document_id")
                    if doc_id:
                        counts[str(doc_id)] = counts.get(str(doc_id), 0) + 1
                if offset is None:
                    break
            counts_source = "qdrant"
        except Exception as exc:  # noqa: BLE001 - counts are additive, not essential
            log.warning("Could not count chunks per document: %s", exc)
            counts = {}

    documents = []
    for doc in docs if isinstance(docs, list) else []:
        entry = dict(doc)
        # source_path is a repo-relative path; the file itself is not served.
        entry.pop("source_path", None)
        entry["indexed_chunks"] = counts.get(str(doc.get("document_id")))
        documents.append(entry)

    return {
        "documents": documents,
        "n_documents": len(documents),
        "total_indexed_chunks": sum(counts.values()) if counts else None,
        "chunk_counts_source": counts_source,
        "provenance": {
            "file": "data/processed/document_metadata.json",
            "sha256": docs_sha,
        },
    }


@app.get(
    "/v1/evaluation",
    summary="The frozen retrieval evaluation",
    description=(
        "Serves eval/final_evaluation_results.json and "
        "eval/final_evaluation_summary.json verbatim, with the SHA-256 of the "
        "bytes read. Nothing is recomputed here — these are the published "
        "numbers, not a live rerun, and this endpoint has no way to produce "
        "any other value."
    ),
    tags=["meta"],
)
def get_evaluation() -> dict[str, Any]:
    results, results_sha = _frozen_or_503("evaluation_results")
    summary, summary_sha = _frozen_or_503("evaluation_summary")

    try:
        integrity, integrity_sha = _read_frozen("integrity_report")
    except Exception:  # noqa: BLE001 - the integrity report is optional
        integrity, integrity_sha = None, None

    return {
        "frozen": True,
        "shipped_config": "V1_atomic_pagesafe",
        "metrics": results.get("metrics", {}),
        "embedding_model": results.get("embedding_model"),
        "embedding_revision": results.get("embedding_revision"),
        "retrieval": results.get("retrieval"),
        "eval_depth": results.get("eval_depth"),
        "gold_sha256": results.get("gold_sha256"),
        "datasets_are_separate": results.get("datasets_are_separate"),
        "chunk_profiles": results.get("chunk_profiles", {}),
        "evidence_statistics": summary.get("evidence_statistics"),
        "final_interpretation": summary.get("final_interpretation"),
        "limitations": summary.get("limitations", []),
        "heldout_selection_rule": summary.get("heldout_selection_rule"),
        "integrity": (
            {
                "all_checks_passed": integrity.get("all_checks_passed"),
                "summary": integrity.get("summary"),
                "checks": integrity.get("checks", []),
            }
            if isinstance(integrity, dict)
            else None
        ),
        "provenance": {
            "final_evaluation_results.json": results_sha,
            "final_evaluation_summary.json": summary_sha,
            "integrity_report.json": integrity_sha,
        },
    }


@app.get(
    "/v1/chunks/{chunk_id}",
    summary="Retrieve chunk by ID",
    description=(
        "Fetches the full payload of a known chunk from Qdrant by its chunk_id "
        "(e.g. 'ESVS_2024__p26-26__c0093'). Used for audit and citation review."
    ),
    tags=["rag"],
)
def get_chunk(chunk_id: str) -> dict[str, Any]:
    retriever = _require_retriever()

    try:
        chunks = retriever.get_by_chunk_ids([chunk_id])
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Qdrant unavailable: {exc}",
        ) from exc

    if not chunks or chunk_id not in chunks:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Chunk '{chunk_id}' not found in the collection.",
        )

    return chunks[chunk_id]
