# -*- coding: utf-8 -*-
"""Clinical RAG FastAPI service.

Thin transport layer around the existing retrieval/generation pipeline.
No core logic lives here — the pipeline is called as-is and its full
GenerationResult is serialised and returned.

Run with:
    uvicorn api.main:app --reload

Endpoints
---------
GET  /health            — API, Qdrant connectivity, and index status.
GET  /v1/meta           — Model/collection metadata.
POST /v1/answer         — Answer a clinical question (calls pipeline.answer_question).
GET  /v1/chunks/{id}    — Retrieve a chunk by its chunk_id.
GET  /docs              — Swagger UI (auto-generated by FastAPI).
GET  /redoc             — ReDoc UI (auto-generated by FastAPI).
"""
from __future__ import annotations

import logging
import sys
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

# Ensure project root is on the path so imports work regardless of cwd
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from generation.pipeline import answer_question  # noqa: E402
from generation.providers import MissingAPIKeyError  # noqa: E402
from vectordb.retriever import QdrantRetriever  # noqa: E402
from vectordb.schema import EXPECTED_DIM, EXPECTED_MODEL, EXPECTED_REVISION  # noqa: E402

log = logging.getLogger("clinical_rag.api")

# ---------------------------------------------------------------------------
# Application state — one retriever (with one embedded model) for the process
# ---------------------------------------------------------------------------

_retriever: QdrantRetriever | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup: initialise retriever and warm the embedding model.

    We intentionally do NOT crash on failure so that /health can report the
    error gracefully and the service remains queryable for diagnostics.
    """
    global _retriever
    try:
        _retriever = QdrantRetriever()
        # Touch the model property so it is loaded once at startup, not on the
        # first /v1/answer request (which would add latency for that caller).
        _ = _retriever.model
        log.info(
            "Retriever ready — collection=%s  model=%s",
            _retriever.settings.collection,
            _retriever.model_name,
        )
    except Exception as exc:  # noqa: BLE001
        log.error("Failed to initialise retriever: %s", exc)
    yield
    # No explicit teardown required for the in-process Qdrant client.


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Clinical RAG API",
    description=(
        "Thin FastAPI service layer over the AAA clinical guideline RAG pipeline. "
        "Calls the existing retrieval and generation logic without modification."
    ),
    version="1.0.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------

class AnswerRequest(BaseModel):
    """Body for POST /v1/answer."""

    question: str = Field(
        ...,
        description="The clinical guideline question to answer.",
        min_length=1,
        examples=["What diameter threshold triggers elective AAA repair?"],
    )
    top_k: int | None = Field(
        None,
        ge=1,
        description="Number of chunks to retrieve from the vector store. "
                    "Defaults to the value configured in generation settings.",
    )
    threshold: float | None = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Minimum similarity score for a chunk to be used as evidence. "
                    "Defaults to the configured score threshold (0.75).",
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _require_retriever() -> QdrantRetriever:
    if _retriever is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "Retriever not initialised. Qdrant may be unavailable or the "
                "embedding model failed to load at startup."
            ),
        )
    return _retriever


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get(
    "/health",
    summary="Health check",
    description="Returns API status, Qdrant connectivity, and index readiness.",
    tags=["ops"],
)
def health_check() -> dict[str, Any]:
    qdrant_ok = False
    index_ok = False

    if _retriever is not None:
        try:
            col_info = _retriever.client.get_collection(_retriever.settings.collection)
            qdrant_ok = True
            index_ok = col_info.status.name == "GREEN"
        except Exception:  # noqa: BLE001
            pass

    return {
        "status": "ok" if (qdrant_ok and index_ok) else "degraded",
        "qdrant": qdrant_ok,
        "index": index_ok,
    }


@app.get(
    "/v1/meta",
    summary="Index and model metadata",
    description="Exposes the pinned model/revision, collection name, dimensions, and chunk count.",
    tags=["meta"],
)
def get_meta() -> dict[str, Any]:
    retriever = _require_retriever()

    try:
        col_info = retriever.client.get_collection(retriever.settings.collection)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Qdrant unavailable: {exc}",
        ) from exc

    return {
        "model": EXPECTED_MODEL,
        "revision": EXPECTED_REVISION,
        "dimensions": EXPECTED_DIM,
        "collection": retriever.settings.collection,
        "chunk_count": col_info.points_count,
        "index_status": col_info.status.name,
    }


@app.post(
    "/v1/answer",
    summary="Answer a clinical question",
    description=(
        "Calls the existing generation pipeline (retrieve → threshold gate → "
        "safety gate → generate → validate) and returns the full GenerationResult. "
        "No fake or fallback answers are produced — if the pipeline refuses, the "
        "refusal reason is included in the response."
    ),
    tags=["rag"],
)
def answer(req: AnswerRequest) -> dict[str, Any]:
    retriever = _require_retriever()

    try:
        result = answer_question(
            query=req.question,
            retriever=retriever,
            top_k=req.top_k,
            threshold=req.threshold,
        )
    except MissingAPIKeyError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"LLM provider API key not configured: {exc}",
        ) from exc
    except ValueError as exc:
        # pipeline.answer_question raises ValueError for an empty/invalid query
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001
        # Qdrant connection error, network timeout, etc.
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(exc),
        ) from exc

    return result.to_dict()


@app.get(
    "/v1/chunks/{chunk_id}",
    summary="Retrieve chunk by ID",
    description=(
        "Fetches the full payload of a known chunk from Qdrant by its chunk_id "
        "(e.g. 'ESVS_2024__p26-26__c0093'). Used for audit and citation review."
    ),
    tags=["rag"],
)
def get_chunk(chunk_id: str) -> dict[str, Any]:
    retriever = _require_retriever()

    try:
        chunks = retriever.get_by_chunk_ids([chunk_id])
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Qdrant unavailable: {exc}",
        ) from exc

    if not chunks or chunk_id not in chunks:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Chunk '{chunk_id}' not found in the collection.",
        )

    return chunks[chunk_id]
